services:
  jenkins:
    image: jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - D:/jenkins_home:/var/jenkins_home:rw
      - D:/Workspace/CSM/csm-front:/tmp/csm-front:rw
      - D:/Workspace/CSM/csm-api/csm-api:/tmp/csm-api:rw
      - D:/Workspace/CSM/csm-api/base-image:/tmp/base-image:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock  # Docker 소켓 설정
      - TZ=Asia/Seoul
    networks:
      - jenkins_internal_network

networks:
  jenkins_internal_network:
    driver: bridge